In [10]:
 #Using NumPy create random vector of size 15 having only Integers in the range 1-20.
    
import numpy as np
#Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type
#of the array.

np_array = np.array([[1, 2, 3], [2, 1, 2],[3,4,5],[5,6,7]], np.int32)
print("Original Numpy array:")
print(np_array)
print("Type: ",type(np_array))
print("Type: ",np_array.dtype)
#Reshape the array to 3 by 5   
x = np.random.randint(1,[20],size=(3,5));
    
# Print array shape.    
print("Random Vector of Size 15:")
print(x)

print("==================================")
max_element = np.amax(x, axis=1)

# this changes the shape of max_elements array so that it matches with input array(a)
# this shape change is done so that we can compare directly
max_element = max_element[:, None]
new_arr = np.where(x == max_element, 0, x)

print(new_arr)
    

Original Numpy array:
[[1 2 3]
 [2 1 2]
 [3 4 5]
 [5 6 7]]
Type:  <class 'numpy.ndarray'>
Type:  int32
Random Vector of Size 15:
[[ 3 16 14  7 10]
 [10  5 15  1  7]
 [18 11 19  6  3]]
[[ 3  0 14  7 10]
 [10  5  0  1  7]
 [18 11  0  6  3]]
