In [1]:
#Clustering & Dimensionality reduction
#Principal Component Analysis
#Apply PCA on CC dataset

import numpy as np
import matplotlib as plt
import pandas as pd
import seaborn as sns
from sklearn import preprocessing ,metrics
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
sns.set(style="white",color_codes=True)
import warnings
warnings.filterwarnings("ignore")

dataSet = pd.read_csv('CC GENERAL.csv')
dataSet.head()

dataSet.isnull().any()
dataSet.fillna(dataSet.mean(),inplace=True)
dataSet.isnull().any()
pca =PCA(3)
x=dataSet.iloc[:,1:-1]
y=dataSet.iloc[:,-1]
print(x.shape,y.shape)

x_pca = pca.fit_transform(x)

principalDf= pd.DataFrame(data= x_pca,columns =['principal component 1','principal component 2','principal component 3'])
finalDf = pd.concat([principalDf,dataSet.iloc[:,-1]],axis=1)
finalDf.head()



(8950, 16) (8950,)


principal component 1  principal component 2  principal component 3  TENURE
0           -4326.383979             921.566882             183.708383      12
1            4118.916665           -2432.846346            2369.969289      12
2            1497.907641           -1997.578694           -2125.631328      12
3            1394.548536           -1488.743453           -2431.799649      12
4           -3743.351896             757.342657             512.476492      12

In [2]:
#Apply k-means algorithm on the PCA result 
X =  finalDf.iloc[:,0:-1]
y =  finalDf.iloc[:,-1]

nclusters=3; #this is k in kmeans
km = KMeans(n_clusters=nclusters)
km.fit(X)

#predict the cluster for each data point
y_cluster_kmeans = km.predict(X)

#Summary of the predictions made by the classifier

print(classification_report(y,y_cluster_kmeans,zero_division=1))
print(confusion_matrix(y,y_cluster_kmeans))

train_accuracy = accuracy_score(y,y_cluster_kmeans)
print("\n Accuracy for our Training Dataset with PCA:",train_accuracy)

#Calculate sihouette Score
score = metrics.silhouette_score(X,y_cluster_kmeans)
print("Silhouette Score:",score)

              precision    recall  f1-score   support

           0       0.00      1.00      0.00       0.0
           1       0.00      1.00      0.00       0.0
           2       0.00      1.00      0.00       0.0
           6       1.00      0.00      0.00     204.0
           7       1.00      0.00      0.00     190.0
           8       1.00      0.00      0.00     196.0
           9       1.00      0.00      0.00     175.0
          10       1.00      0.00      0.00     236.0
          11       1.00      0.00      0.00     365.0
          12       1.00      0.00      0.00    7584.0

    accuracy                           0.00    8950.0
   macro avg       0.70      0.30      0.00    8950.0
weighted avg       1.00      0.00      0.00    8950.0

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   1  175   28    0    0    0    0    0    0    0]
 [   2  173   15    0    0   

In [3]:
X=dataSet.iloc[:,0:-1]
y=dataSet["TENURE"]
print(X.shape,y.shape)

#Scaling
scaler= StandardScaler()
scaler.fit(x)
X_Scaled_Array = scaler.transform(x)

#PCA
pca= PCA(3)
x_pca = pca.fit_transform(X_Scaled_Array)
principalDf= pd.DataFrame(data= x_pca,columns =['principal component 1','principal component 2','principal component 3'])
finalDf = pd.concat([principalDf,dataSet.iloc[:,-1]],axis=1)
finalDf.head()

(8950, 17) (8950,)


principal component 1  principal component 2  principal component 3  TENURE
0              -1.718893              -1.072939               0.535685      12
1              -1.169306               2.509320               0.627986      12
2               0.938414              -0.382600               0.161215      12
3              -0.907503               0.045859               1.521684      12
4              -1.637830              -0.684975               0.425683      12

In [5]:
X =  finalDf.iloc[:,0:-1]
y =  finalDf["TENURE"]
print(X.shape,y.shape)

X_train , X_test, y_train,y_test = train_test_split(X,y,test_size=0.34,random_state=0)
nclusters =3

#this is the k in kmeans
km = KMeans(n_clusters=nclusters)
km.fit(X_train,y_train)

#predict the cluster for each training data point
y_clus_train =km.predict(X_train)

#Summary of the predictions made by the classifier
print(classification_report(y_train,y_clus_train,zero_division=1))
print(confusion_matrix(y_train,y_clus_train))

train_accuracy = accuracy_score(y_train,y_clus_train)
print("\n Accuracy for our Training Dataset with PCA:",train_accuracy)

#Calculate sihouette Score
score = metrics.silhouette_score(X_train,y_clus_train)
print("Silhouette Score:",score)


(8950, 3) (8950,)
              precision    recall  f1-score   support

           0       0.00      1.00      0.00       0.0
           1       0.00      1.00      0.00       0.0
           2       0.00      1.00      0.00       0.0
           6       1.00      0.00      0.00     139.0
           7       1.00      0.00      0.00     135.0
           8       1.00      0.00      0.00     128.0
           9       1.00      0.00      0.00     118.0
          10       1.00      0.00      0.00     151.0
          11       1.00      0.00      0.00     262.0
          12       1.00      0.00      0.00    4974.0

    accuracy                           0.00    5907.0
   macro avg       0.70      0.30      0.00    5907.0
weighted avg       1.00      0.00      0.00    5907.0

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [ 105    4   30    0    0    0    0    0    0    0]
 [ 108    1

In [6]:
#predict the cluster for each testing data point
y_clus_test = km.predict(X_test)

#Summary of the predictions made by the classifier
print(classification_report(y_test,y_clus_test,zero_division=1))
print(confusion_matrix(y_test,y_clus_test))

train_accuracy = accuracy_score(y_test,y_clus_test)
print("\n Accuracy for our Training Dataset with PCA:",train_accuracy)

#Calculate sihouette Score
score = metrics.silhouette_score(X_test,y_clus_test)
print("Silhouette Score:",score)


              precision    recall  f1-score   support

           0       0.00      1.00      0.00       0.0
           1       0.00      1.00      0.00       0.0
           2       0.00      1.00      0.00       0.0
           6       1.00      0.00      0.00      65.0
           7       1.00      0.00      0.00      55.0
           8       1.00      0.00      0.00      68.0
           9       1.00      0.00      0.00      57.0
          10       1.00      0.00      0.00      85.0
          11       1.00      0.00      0.00     103.0
          12       1.00      0.00      0.00    2610.0

    accuracy                           0.00    3043.0
   macro avg       0.70      0.30      0.00    3043.0
weighted avg       1.00      0.00      0.00    3043.0

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [  41    3   21    0    0    0    0    0    0    0]
 [  42    1   12    0    0   